### ISSUE TITLE
Is there a reason most of the binaries are 8 months old?

### ISSUE THREAD

**Issue by BrianGilbert** [eSlider/sassc-binaries#3]

**Comment by eSlider** [comment]
Because of stability and static linking binaries builds. I tried to build new releases with effort and just gets dynamic instable linked large binaries. On the other side I have less time to make new releases and tests they for each plattform. Only if SCSS becomes super new cool features, I will invest time to build new binaries. :)

**Comment by BrianGilbert** [comment]
@eSlider 
Would you be interested in documenting how you compile them, so that others can attempt to do it themselves?

**Comment by eSlider** [comment]
@BrianGilbert, it's already done by origin here: https://github.com/sass/sassc#documentation
